prompt_order = [
    "cmd_duration",
    "directory",
    "python",
    "golang",
    "ruby",
    "rust",
    "memory_usage",
    "kubernetes",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "line_break",
    "jobs",
    "character",
]

[username]
disabled = true
[hostname]
disabled = true

[directory]
prefix = ""
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style)"
symbol = ""
style="$(tput setaf 40)"

[git_status]
ahead = "🚀 "
beind = "✨ "
diverged = "📥 "
staged = "📁 "
untracked = "👀 "
modified = "📝 "
format = " ($all_status$ahead_behind )"
prefix = ""
suffix = ""

[kubernetes]
prefix = ""
symbol = ""
format = "[$symbol$context( \\($namespace\\))]($style) "
style = "fg:#326DE6"
disabled = false
